package br.edu.ufcg.geodengue.client.eventos;

public enum TiposDeEventos {
	CADASTRAR_FOCO_CLICADO,
	CADASTRAR_NOVO_PONTO,
	CADASTRAR_PESSOA_CLICADO,	
	CHECKBOX_AREA_AGENTE,
	CHECKBOX_FOCOS,
	CHECKBOX_PESSOAS_CONTAMINADAS;
}