package br.edu.ufcg.geodengue.client.utils;

public enum Estado {
	AREA_AGENTE,
	CADASTRAR_AGENTE,
	CADASTRAR_FOCO,
	CADASTRAR_PESSOA,
	CALCULAR_PESSOA_RAIO,
	DISTANCIA_DOIS_FOCOS,
	FOCOS_DISTANCIA,
	ROTA,
	SIMULA_DEMITIR;
}