UPDATE bairroscampina SET nome = 'Mirante' WHERE gid = 1;
UPDATE bairroscampina SET nome = 'Castelo Branco' WHERE gid = 2;
UPDATE bairroscampina SET nome = 'Vila Cabral' WHERE gid = 3;
UPDATE bairroscampina SET nome = 'Sandra Cavalcante' WHERE gid = 4;
UPDATE bairroscampina SET nome = 'Jose Pinheiro' WHERE gid = 5;
UPDATE bairroscampina SET nome = 'Cruzeiro' WHERE gid = 6;
UPDATE bairroscampina SET nome = 'Centenario' WHERE gid = 7;
UPDATE bairroscampina SET nome = 'Santa Rosa' WHERE gid = 8;
UPDATE bairroscampina SET nome = 'Bela Vista' WHERE gid = 9;
UPDATE bairroscampina SET nome = 'Monte Santo' WHERE gid = 10;
UPDATE bairroscampina SET nome = 'Bairro Universitario' WHERE gid = 11;
UPDATE bairroscampina SET nome = 'Distrito industrial' WHERE gid = 12;
UPDATE bairroscampina SET nome = 'Dinamerica' WHERE gid = 13;
UPDATE bairroscampina SET nome = 'Malvinas' WHERE gid = 14;
UPDATE bairroscampina SET nome = 'Acacio Figueiredo' WHERE gid = 15;
UPDATE bairroscampina SET nome = 'Bodocongo' WHERE gid = 16;
UPDATE bairroscampina SET nome = 'Novo Bodocongo' WHERE gid = 17;
UPDATE bairroscampina SET nome = 'Ramadinha' WHERE gid = 18;
UPDATE bairroscampina SET nome = 'Pedregal' WHERE gid = 19;
UPDATE bairroscampina SET nome = 'Santa Cruz' WHERE gid = 20;
UPDATE bairroscampina SET nome = 'Sao Jose' WHERE gid = 21;
UPDATE bairroscampina SET nome = 'Estacao Velha' WHERE gid = 22;
UPDATE bairroscampina SET nome = 'Tambor' WHERE gid = 23;
UPDATE bairroscampina SET nome = 'Centro' WHERE gid = 24;
UPDATE bairroscampina SET nome = 'Alto Branco' WHERE gid = 25;
UPDATE bairroscampina SET nome = 'Conceicao' WHERE gid = 26;
UPDATE bairroscampina SET nome = 'Liberdade' WHERE gid = 27;
UPDATE bairroscampina SET nome = 'Quarenta' WHERE gid = 28;
UPDATE bairroscampina SET nome = 'Prata' WHERE gid = 29;
UPDATE bairroscampina SET nome = 'Palmeira' WHERE gid = 30;
UPDATE bairroscampina SET nome = 'Itarare' WHERE gid = 31;
UPDATE bairroscampina SET nome = 'Santo Antonio' WHERE gid = 32;
UPDATE bairroscampina SET nome = 'Nova Brasilia' WHERE gid = 33;
UPDATE bairroscampina SET nome = 'Jeremias' WHERE gid = 34;
UPDATE bairroscampina SET nome = 'Serrotao' WHERE gid = 35;
UPDATE bairroscampina SET nome = 'Velame' WHERE gid = 36;
UPDATE bairroscampina SET nome = 'Jardim Tavares' WHERE gid = 37;
UPDATE bairroscampina SET nome = 'Cuites' WHERE gid = 38;
UPDATE bairroscampina SET nome = 'Monte Castelo' WHERE gid = 39;
UPDATE bairroscampina SET nome = 'Bairro das Cidades' WHERE gid = 40;
UPDATE bairroscampina SET nome = 'Louzeiro' WHERE gid = 41;
UPDATE bairroscampina SET nome = 'Jardim Continental' WHERE gid = 42;
UPDATE bairroscampina SET nome = 'Bairro das Nacoes' WHERE gid = 43;
UPDATE bairroscampina SET nome = 'Araxa' WHERE gid = 44;
UPDATE bairroscampina SET nome = 'Presidente Medice' WHERE gid = 45;
UPDATE bairroscampina SET nome = 'Tres Irmas' WHERE gid = 46;
UPDATE bairroscampina SET nome = 'Jardim Paulistano' WHERE gid = 47;
UPDATE bairroscampina SET nome = 'Santa Terezinha' WHERE gid = 48;
UPDATE bairroscampina SET nome = 'Lauritzen' WHERE gid = 49;
UPDATE bairroscampina SET nome = 'Catole' WHERE gid = 50;